# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(741, 609)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setMinimumSize(QtCore.QSize(175, 550))
        self.toolBox.setMaximumSize(QtCore.QSize(175, 700))
        self.toolBox.setStyleSheet("QToolBox::tab {\n"
"    background: lightgray;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"}\n"
"\n"
"QToolBox::tab:selected { /* italicize selected tabs */\n"
"    font: italic;\n"
"    background: lightgray;\n"
"    color: darkgray;\n"
"}\n"
"")
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolBox.setObjectName("toolBox")
        self.calibrationPage = QtWidgets.QWidget()
        self.calibrationPage.setGeometry(QtCore.QRect(0, 0, 175, 460))
        self.calibrationPage.setObjectName("calibrationPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.calibrationPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.calibrationPage)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cali_load = QtWidgets.QPushButton(self.groupBox)
        self.cali_load.setObjectName("cali_load")
        self.verticalLayout_4.addWidget(self.cali_load)
        self.calibrationDisplay = QtWidgets.QLabel(self.groupBox)
        self.calibrationDisplay.setMinimumSize(QtCore.QSize(137, 114))
        self.calibrationDisplay.setMaximumSize(QtCore.QSize(137, 114))
        self.calibrationDisplay.setFrameShape(QtWidgets.QFrame.Box)
        self.calibrationDisplay.setLineWidth(1)
        self.calibrationDisplay.setText("")
        self.calibrationDisplay.setPixmap(QtGui.QPixmap("../../1x/imagePlaceholder.png"))
        self.calibrationDisplay.setScaledContents(True)
        self.calibrationDisplay.setObjectName("calibrationDisplay")
        self.verticalLayout_4.addWidget(self.calibrationDisplay)
        self.cali_s_label = QtWidgets.QLabel(self.groupBox)
        self.cali_s_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cali_s_label.setObjectName("cali_s_label")
        self.verticalLayout_4.addWidget(self.cali_s_label)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.get_tform = QtWidgets.QPushButton(self.calibrationPage)
        self.get_tform.setObjectName("get_tform")
        self.verticalLayout_3.addWidget(self.get_tform)
        self.cali_tform_success = QtWidgets.QLabel(self.calibrationPage)
        self.cali_tform_success.setStyleSheet("color: red")
        self.cali_tform_success.setAlignment(QtCore.Qt.AlignCenter)
        self.cali_tform_success.setObjectName("cali_tform_success")
        self.verticalLayout_3.addWidget(self.cali_tform_success)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.toolBox.addItem(self.calibrationPage, "")
        self.AnalysisPage = QtWidgets.QWidget()
        self.AnalysisPage.setGeometry(QtCore.QRect(0, 0, 175, 460))
        self.AnalysisPage.setObjectName("AnalysisPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.AnalysisPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.AnalysisPage)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.analysis_load = QtWidgets.QPushButton(self.groupBox_3)
        self.analysis_load.setObjectName("analysis_load")
        self.verticalLayout_6.addWidget(self.analysis_load)
        self.rawImageDisplay = QtWidgets.QLabel(self.groupBox_3)
        self.rawImageDisplay.setMinimumSize(QtCore.QSize(137, 114))
        self.rawImageDisplay.setMaximumSize(QtCore.QSize(137, 114))
        self.rawImageDisplay.setFrameShape(QtWidgets.QFrame.Box)
        self.rawImageDisplay.setLineWidth(1)
        self.rawImageDisplay.setText("")
        self.rawImageDisplay.setPixmap(QtGui.QPixmap("../../1x/imagePlaceholder.png"))
        self.rawImageDisplay.setScaledContents(True)
        self.rawImageDisplay.setObjectName("rawImageDisplay")
        self.verticalLayout_6.addWidget(self.rawImageDisplay)
        self.analysis_s_label = QtWidgets.QLabel(self.groupBox_3)
        self.analysis_s_label.setAlignment(QtCore.Qt.AlignCenter)
        self.analysis_s_label.setObjectName("analysis_s_label")
        self.verticalLayout_6.addWidget(self.analysis_s_label)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.AnalysisPage)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.analyse = QtWidgets.QPushButton(self.groupBox_4)
        self.analyse.setObjectName("analyse")
        self.verticalLayout_7.addWidget(self.analyse)
        self.resultImageDisplay = QtWidgets.QLabel(self.groupBox_4)
        self.resultImageDisplay.setMinimumSize(QtCore.QSize(137, 114))
        self.resultImageDisplay.setMaximumSize(QtCore.QSize(137, 114))
        self.resultImageDisplay.setFrameShape(QtWidgets.QFrame.Box)
        self.resultImageDisplay.setLineWidth(1)
        self.resultImageDisplay.setText("")
        self.resultImageDisplay.setPixmap(QtGui.QPixmap("../../1x/imagePlaceholder.png"))
        self.resultImageDisplay.setScaledContents(True)
        self.resultImageDisplay.setObjectName("resultImageDisplay")
        self.verticalLayout_7.addWidget(self.resultImageDisplay)
        self.analysis_result = QtWidgets.QLabel(self.groupBox_4)
        self.analysis_result.setObjectName("analysis_result")
        self.verticalLayout_7.addWidget(self.analysis_result)
        self.verticalLayout.addWidget(self.groupBox_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 162, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.toolBox.addItem(self.AnalysisPage, "")
        self.ExportPage = QtWidgets.QWidget()
        self.ExportPage.setGeometry(QtCore.QRect(0, 0, 175, 460))
        self.ExportPage.setObjectName("ExportPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ExportPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.export_button = QtWidgets.QPushButton(self.ExportPage)
        self.export_button.setObjectName("export_button")
        self.verticalLayout_2.addWidget(self.export_button)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.toolBox.addItem(self.ExportPage, "")
        self.horizontalLayout.addWidget(self.toolBox)
        self.chartFrame = QtWidgets.QFrame(self.centralwidget)
        self.chartFrame.setMinimumSize(QtCore.QSize(540, 540))
        self.chartFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.chartFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chartFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.chartFrame.setObjectName("chartFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.chartFrame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout.addWidget(self.chartFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 741, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Import"))
        self.cali_load.setText(_translate("MainWindow", "Load image"))
        self.cali_s_label.setText(_translate("MainWindow", "Image( ... , ... )"))
        self.get_tform.setText(_translate("MainWindow", "Get tform"))
        self.cali_tform_success.setText(_translate("MainWindow", "tform: not run yet"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.calibrationPage), _translate("MainWindow", "Calibration"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Import"))
        self.analysis_load.setText(_translate("MainWindow", "Load image"))
        self.analysis_s_label.setText(_translate("MainWindow", "Image( ... , ... )"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Analysis"))
        self.analyse.setText(_translate("MainWindow", "Analyse"))
        self.analysis_result.setText(_translate("MainWindow", "#px: "))
        self.toolBox.setItemText(self.toolBox.indexOf(self.AnalysisPage), _translate("MainWindow", "Analysis"))
        self.export_button.setText(_translate("MainWindow", "Export"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ExportPage), _translate("MainWindow", "Export to DXF"))
